SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `uid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(1024) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `school` VARCHAR(255) NULL DEFAULT NULL,
  `localstatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `mydb`.`problem` (
  `pid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(1024) NULL DEFAULT NULL,
  `originOJ` VARCHAR(255) NULL DEFAULT NULL,
  `originProb` VARCHAR(45) NULL DEFAULT NULL,
  `memorylimit` VARCHAR(45) NULL DEFAULT NULL,
  `timelimit` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `mydb`.`problemdetail` (
  `did` INT(11) NOT NULL AUTO_INCREMENT,
  `pid` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `input` TEXT NULL DEFAULT NULL,
  `output` TEXT NULL DEFAULT NULL,
  `sampleinput` TEXT NULL DEFAULT NULL,
  `sampleoutput` TEXT NULL DEFAULT NULL,
  `hint` TEXT NULL DEFAULT NULL,
  `author` VARCHAR(255) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `updateTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`did`),
  INDEX `fk_problemdetail_1_idx` (`pid` ASC),
  CONSTRAINT `fk_problemdetail_1`
    FOREIGN KEY (`pid`)
    REFERENCES `mydb`.`problem` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `mydb`.`contest` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT,
  `ctitle` VARCHAR(255) NULL DEFAULT NULL,
  `cdescription` TEXT NULL DEFAULT NULL,
  `announcement` TEXT NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `begintime` DATETIME NULL DEFAULT NULL,
  `endtime` DATETIME NULL DEFAULT NULL,
  `hashcode` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `mydb`.`cproblem` (
  `cpid` INT(11) NOT NULL AUTO_INCREMENT,
  `cid` INT(11) NULL DEFAULT NULL,
  `pid` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cpid`),
  INDEX `fk_cproblem_1_idx` (`cid` ASC),
  INDEX `fk_cproblem_2_idx` (`pid` ASC),
  CONSTRAINT `fk_cproblem_1`
    FOREIGN KEY (`cid`)
    REFERENCES `mydb`.`contest` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cproblem_2`
    FOREIGN KEY (`pid`)
    REFERENCES `mydb`.`problem` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `runid` INT(11) NOT NULL AUTO_INCREMENT,
  `timesubmit` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  `runtime` VARCHAR(45) NULL DEFAULT NULL,
  `runmemory` VARCHAR(45) NULL DEFAULT NULL,
  `pid` INT(11) NULL DEFAULT NULL,
  `cid` INT(11) NULL DEFAULT NULL,
  `language` VARCHAR(45) NULL DEFAULT NULL,
  `source` TEXT NULL DEFAULT NULL,
  `isopen` TINYINT(1) NULL DEFAULT NULL,
  `uid` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `originOJ` VARCHAR(255) NULL DEFAULT NULL,
  `originProb` VARCHAR(45) NULL DEFAULT NULL,
  `realrunid` VARCHAR(45) NULL DEFAULT NULL,
  `isdisplay` TINYINT(1) NULL DEFAULT NULL,
  `ceinfo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`runid`),
  INDEX `fk_status_1_idx` (`pid` ASC),
  CONSTRAINT `fk_status_1`
    FOREIGN KEY (`pid`)
    REFERENCES `mydb`.`problem` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

