Bzoj_LogIn_Url = 'http://www.lydsy.com/JudgeOnline/login.php'

BzojUser = [
    dict(
        user_id='VirtualJudgePY',
        password='123456l',
        submit='Submit',
        vj_username='VirtualJudgePY',
    ),
    dict(
        user_id='xtuvj1',
        password='dowhile1',
        submit='Submit',
        vj_username='xtuvj1',
    ),
    dict(
        user_id='xtuvj2',
        password='dowhile2',
        submit='Submit',
        vj_username='xtuvj2',
    ),
    dict(
        user_id='xtuvj3',
        password='dowhile3',
        submit='Submit',
        vj_username='xtuvj3',
    ),
    dict(
        user_id='xtuvj4',
        password='dowhile4',
        submit='Submit',
        vj_username='xtuvj4',
    ),
    dict(
        user_id='xtuvj5',
        password='dowhile5',
        submit='Submit',
        vj_username='xtuvj5',
    ),
]
